#Pandas All Concepts

In [104]:
# importing pandas
import numpy as np
import pandas as pd

##Series made from Lists

In [105]:
# Series -> columns in the table are called series in pandas. Series is a class inside pandas.
country = ['India','Pakistan','China','Srilanka']
pd.Series(country)

# Notes: In pandas , when we get dtype: object , it means values are in string form. Not in everycase but most of the cases.
#        Series include two things: index and values
#        country is as object of 'Series' class

0       India
1    Pakistan
2       China
3    Srilanka
dtype: object

In [106]:
# integers
runs = [13,45,77,23,55]
pd.Series(runs)

0    13
1    45
2    77
3    23
4    55
dtype: int64

In [107]:
# custom index
marks = [67,69,99,10]
subjects = ['maths','science','english','french']

custom = pd.Series(marks,index=subjects)
print(custom)

maths      67
science    69
english    99
french     10
dtype: int64

In [108]:
# setting a name
y = pd.Series(marks,index=subjects,name='Marks of Mayank')
print(y)

maths      67
science    69
english    99
french     10
Name: Marks of Mayank, dtype: int64

##Series made from dictionary

In [109]:
marks = {
    'English':69,
    'Hindi':100,
    'Computer science':100
}

marks_dict = pd.Series(marks)
print(marks_dict)

English              69
Hindi               100
Computer science    100
dtype: int64

##Series Attributes

In [110]:
# size
marks_dict.size

3

In [111]:
y.size

4

In [112]:
# dtype
y.dtype

dtype('int64')

In [113]:
# name
y.name

'Marks of Mayank'

In [114]:
# is_unique -> tells about all the elements of the series are unique of not
y.is_unique

True

In [115]:
# index
y.index

Index(['maths', 'science', 'english', 'french'], dtype='object')

In [116]:
runs = pd.Series([13,45,77,23,55])
runs.index

# RangeIndex is just a special kind of object which store index values

RangeIndex(start=0, stop=5, step=1)

In [117]:
# values -> gives a numpy array
y.values

array([67, 69, 99, 10])

##Series using read_csv

In [118]:
# with 1 column
subs = pd.read_csv('/content/subs.csv')
print(subs)

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [119]:
# with 2 column
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')
print(vk)

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [120]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie')
print(movies)

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

##Series Methods

In [121]:
# head and tail
# head -> give data preview only , show first 5 rows from data by dafault BUT we can ask for more by mentioning no. of rows in head()

print(subs.head())

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [122]:
print(vk.tail())

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [123]:
# sample -> give one row from data randomly
# useful when our data has some bias
print(movies.sample(3))

                                lead
movie
Ghajini (2008 film)       Aamir Khan
Baby (2015 Hindi film)  Akshay Kumar
No Entry                 Anil Kapoor

In [124]:
# value_counts -> tells the frequency for a value present in data in DESC order
print(movies.value_counts())

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Naveen Bawa          1
Naushaad Abbas       1
Nauheed Cyrusi       1
Natalia Janoszek     1
Nishikant Kamat      1
Name: count, Length: 566, dtype: int64

In [125]:
# sort_values
print(vk.sort_values(by='runs',ascending=False))

          runs
match_no
128        113
126        109
123        108
120        100
164        100
...        ...
93           0
130          0
206          0
207          0
211          0

[215 rows x 1 columns]

In [126]:
# we can use head() here also
# THIS IS CALLED METHOD CHAINING
print(vk.sort_values(by='runs',ascending=False).head(3).values[0])

[113]

In [127]:
# if you want to do permanent changes in dataset , you have to use inplace=True
vk.sort_values(by='runs',inplace=True)

In [128]:
print(vk)

          runs
match_no
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [129]:
# sort_index
print(movies.sort_index())

                                        lead
movie
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Arjun Kapoor
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

##Series Maths Methods

In [130]:
# count -> give count of elements but dont consider missing values
# size -> do same work but consider missing values

print(vk.count())
print()
print(vk.size)

runs    215
dtype: int64

215

In [131]:
# sum
print(subs.sum())

Subscribers gained    49510
dtype: int64

In [132]:
# product
print(subs.product())

Subscribers gained    0
dtype: int64

In [133]:
# mean
print(subs.mean())

Subscribers gained    135.643836
dtype: float64

In [134]:
# median
print(vk.median())

runs    24.0
dtype: float64

In [135]:
# mode -> which value has highest frequency
print(movies.mode())

           lead
0  Akshay Kumar

In [136]:
# std (standard deviation)
print(subs.std())

Subscribers gained    62.675023
dtype: float64

In [137]:
# var (variance)
print(vk.var())

runs    688.002478
dtype: float64

In [138]:
# min/max
print(subs.min())

Subscribers gained    33
dtype: int64

In [139]:
# describe -> give summary
print(vk.describe())

             runs
count  215.000000
mean    30.855814
std     26.229801
min      0.000000
25%      9.000000
50%     24.000000
75%     48.000000
max    113.000000

##Series Indexing

In [140]:
# integer indexing
x = pd.Series([12,13,14,35,77,2,1,9])
x[0]

np.int64(12)

In [141]:
# negative indexing series
# DOES NOT WORKS

In [142]:
# fetching value from giving index
print(movies.iloc[0])

lead    Vicky Kaushal
Name: Uri: The Surgical Strike, dtype: object

In [143]:
print(movies.iloc[-1])

lead    Akshay Kumar
Name: Awara Paagal Deewana, dtype: object

In [144]:
print(vk.iloc[0])

runs    0
Name: 8, dtype: int64

In [145]:
# Slicing
print(vk[5:16])

          runs
match_no
207          0
135          0
130          0
211          0
106          1
204          1
113          1
77           1
1            1
5            1
75           1

In [146]:
print(vk[-5:])

          runs
match_no
164        100
120        100
123        108
126        109
128        113

In [147]:
print(movies[-5:])

                                    lead
movie
Hum Tumhare Hain Sanam    Shah Rukh Khan
Aankhen (2002 film)     Amitabh Bachchan
Saathiya (film)             Vivek Oberoi
Company (film)                Ajay Devgn
Awara Paagal Deewana        Akshay Kumar

In [148]:
print(movies[::2])

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
The Accidental Prime Minister (film)       Anupam Kher
Evening Shadows                       Mona Ambegaonkar
Fraud Saiyaan                             Arshad Warsi
Manikarnika: The Queen of Jhansi        Kangana Ranaut
...                                                ...
Raaz (2002 film)                            Dino Morea
Waisa Bhi Hota Hai Part II                Arshad Warsi
Kaante                                Amitabh Bachchan
Aankhen (2002 film)                   Amitabh Bachchan
Company (film)                              Ajay Devgn

[750 rows x 1 columns]

In [149]:
# fancy indexing
print(vk.iloc[[1,3,4,5]])

          runs
match_no
87           0
91           0
206          0
207          0

In [150]:
# indexing with labels
print(movies.loc['The Accidental Prime Minister (film)'])

lead    Anupam Kher
Name: The Accidental Prime Minister (film), dtype: object

##Editing Series

In [151]:
# using indexing
custom

maths      67
science    69
english    99
french     10
dtype: int64

In [152]:
custom['sst'] = 100

In [153]:
print(custom)

maths       67
science     69
english     99
french      10
sst        100
dtype: int64

In [154]:
# slicing
runs[2:4] = [100,100]
print(runs)

0     13
1     45
2    100
3    100
4     55
dtype: int64

In [155]:
# fancy indexing
runs[[0,3,4]] = [0,0,0]

In [156]:
print(runs)

0      0
1     45
2    100
3      0
4      0
dtype: int64

In [157]:
# using index label
# movies['2 States (2014 film)'] = 'Alia Bhatt'

In [158]:
print(movies.loc['2 States (2014 film)'])

lead    Arjun Kapoor
Name: 2 States (2014 film), dtype: object

##Series with python functionalities

In [159]:
# len/type/dir/sorted/min/max
print(len(subs))
print(type(subs))

365
<class 'pandas.core.frame.DataFrame'>

In [160]:
# dir -> show all attributes applicable
print(dir(subs))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_arith_method_with_reindex', '_as_manager', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_create_data_for_split_and_tight_to_dict', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item_cache', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_nocopy', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_copy', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_item_cache', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bigquery', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_geometry', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [161]:
print(sorted(subs))

['Subscribers gained']

In [162]:
# sorted -> sort plus give output in list format
print(subs['Subscribers gained'].sort_values().to_list())

[33, 33, 35, 37, 39, 40, 40, 40, 40, 42, 42, 43, 44, 44, 44, 45, 46, 46, 48, 49, 49, 49, 49, 50, 50, 50, 51, 54, 56, 56, 56, 56, 57, 61, 62, 64, 65, 65, 66, 66, 66, 66, 67, 68, 70, 70, 70, 71, 71, 72, 72, 72, 72, 72, 73, 74, 74, 75, 76, 76, 76, 76, 77, 77, 78, 78, 78, 79, 79, 80, 80, 80, 81, 81, 82, 82, 83, 83, 83, 84, 84, 84, 85, 86, 86, 86, 87, 87, 87, 87, 88, 88, 88, 88, 88, 89, 89, 89, 90, 90, 90, 90, 91, 92, 92, 92, 93, 93, 93, 93, 95, 95, 96, 96, 96, 96, 97, 97, 98, 98, 99, 99, 100, 100, 100, 101, 101, 101, 102, 102, 103, 103, 104, 104, 104, 105, 105, 105, 105, 105, 105, 105, 105, 105, 108, 108, 108, 108, 108, 108, 109, 109, 110, 110, 110, 111, 111, 112, 113, 113, 113, 114, 114, 114, 114, 115, 115, 115, 115, 117, 117, 117, 118, 118, 119, 119, 119, 119, 120, 122, 123, 123, 123, 123, 123, 124, 125, 126, 127, 128, 128, 129, 130, 131, 131, 132, 132, 134, 134, 134, 135, 135, 136, 136, 136, 137, 138, 138, 138, 139, 140, 144, 145, 146, 146, 146, 146, 147, 149, 150, 150, 150, 150, 151, 152, 152, 152, 153, 153, 153, 154, 154, 154, 155, 155, 156, 156, 156, 156, 157, 157, 157, 157, 158, 158, 159, 159, 160, 160, 160, 160, 162, 164, 166, 167, 167, 168, 170, 170, 170, 170, 171, 172, 172, 173, 173, 173, 174, 174, 175, 175, 176, 176, 177, 178, 179, 179, 180, 180, 180, 182, 183, 183, 183, 184, 184, 184, 185, 185, 185, 185, 186, 186, 186, 188, 189, 190, 190, 192, 192, 192, 196, 196, 196, 197, 197, 202, 202, 202, 203, 204, 206, 207, 209, 210, 210, 211, 212, 213, 214, 216, 219, 220, 221, 221, 222, 222, 224, 225, 225, 226, 227, 228, 229, 230, 231, 233, 236, 236, 237, 241, 243, 244, 245, 247, 249, 254, 254, 258, 259, 259, 261, 261, 265, 267, 268, 269, 276, 276, 290, 295, 301, 306, 312, 396]

In [163]:
print(subs['Subscribers gained'].min())

33

In [164]:
print(subs['Subscribers gained'].max())

396

In [165]:
# type conversion
list(custom)

[67, 69, 99, 10, 100]

In [166]:
dict(custom)

{'maths': np.int64(67),
 'science': np.int64(69),
 'english': np.int64(99),
 'french': np.int64(10),
 'sst': np.int64(100)}

In [167]:
# membership operator generally for indexes
'Why Cheat India' in movies.index

True

In [168]:
'Alia Bhatt' in movies.values

True

In [169]:
# looping -> use for values
for i in movies.values:
  print(i)

['Vicky Kaushal']
['Vicky Ahuja']
['Anupam Kher']
['Emraan Hashmi']
['Mona Ambegaonkar']
['Geetika Vidya Ohlyan']
['Arshad Warsi']
['Radhika Apte']
['Kangana Ranaut']
['Nawazuddin Siddiqui']
['Ali Asgar']
['Ranveer Singh']
['Prit Kamani']
['Ajay Devgn']
['Sushant Singh Rajput']
['Amitabh Bachchan']
['Abhimanyu Dasani']
['Talha Arshad Reshi']
['Nawazuddin Siddiqui']
['Garima Agarwal']
['Rasika Agashe']
['Barun Sobti']
['Akshay Kumar']
['Zaheer Iqbal']
['Vidyut Jammwal']
['Deepika Amin']
['Manav Kaul']
['Naseeruddin Shah']
['Varun Dhawan']
['Shreyas Talpade']
['Tiger Shroff']
['Boman Irani']
['Ajay Devgn']
['Arjun Kapoor']
['Gavie Chahal']
['Prabhu Deva']
['Shahid Kapoor']
['Ayushmann Khurrana']
['Anupam Kher']
['Karanvir Bohra']
['Hrithik Roshan']
['Jimmy Sheirgill']
['John Abraham']
['Rishi Kapoor']
['Kangana Ranaut']
['Natalia Janoszek']
['Diljit Dosanjh']
['Sidharth Malhotra']
['Rajeev Khandelwal']
['Zaira Wasim']
['Akshay Kumar']
['Jacqueline Fernandez']
['Ayushmann Khurrana']
['Akshaye Khanna']
['Sonam Kapoor']
['Karan Deol']
['Sanjay Dutt']
['Bhavesh Kumar']
['Sanaya Irani']
['Ayushmann Khurrana']
['Siddhanth Kapoor']
['Akshay Kumar']
['Taapsee Pannu']
['Rajkummar Rao']
['Sunny Singh Nijjar']
['Neil Nitin Mukesh']
['Suraj Pancholi']
['Boman Irani']
['Riteish Deshmukh']
['Nawazuddin Siddiqui']
['Shahbaaz Khan']
['Kriti Kharbanda']
['Naseeruddin Shah']
['Vardhan Puri']
['Sushant Singh Rajput']
['Kartik Aaryan']
['Vidyut Jammwal']
['Rani Mukerji']
['Salman Khan']
['Akshay Kumar']
['Saif Ali Khan']
['Kay Kay Menon']
['Nora Fatehi']
['Ashmit Patel']
['Viineet Kumar']
['Rahul Bhat']
['Vicky Kaushal']
['Sidharth Malhotra']
['Deepika Padukone']
['Geetanjali Thapa']
['Akshay Anand']
['Pulkit Samrat']
['Kartik Aaryan']
['Lee Byford']
['Taapsee Pannu']
['Aisha Ahmed']
['Ajay Devgn']
['Rani Mukerji']
['Manoj Bajpayee']
['Tiger Shroff']
['Varun Dhawan']
['Prabhu Deva']
['Ishaan Khattar']
['Abhay Deol']
['Yogesh Raj Mishra']
['Rajkummar Rao']
['Alia Bhatt']
['Naseeruddin Shah']
['Sumeet Vyas']
['Vinay Pathak']
['John Abraham']
['Danny Denzongpa']
['Harshvardhan Kapoor']
['Jimmy Sheirgill']
['Anil Kapoor']
['Ishaan Khattar']
['Ranbir Kapoor']
['Sanjay Dutt']
['Dharmesh Yelande']
['Taapsee Pannu']
['Arjun Mathur']
['Irrfan Khan']
['Akshay Kumar']
['John Abraham']
['Sonakshi Sinha']
['Utkarsh Sharma']
['Dharmendra']
['Rajkummar Rao']
['Jackie Shroff']
['Avinash Tiwary']
['Manoj Bajpayee']
['Paoli Dam']
['Sanya Malhotra']
['Shahid Kapoor']
['Abhishek Bharate']
['Nawazuddin Siddiqui']
['Manish Anand']
['Taapsee Pannu']
['Jackky Bhagnani']
['Anushka Sharma']
['Radhika Apte']
['Rhea Chakraborty']
['Govinda']
['Sohum Shah']
['Kajol']
['Arjun Kapoor']
['Ayushmann Khurrana']
['Ayushmann Khurrana']
['Nargis Fakhri']
['Aishwarya Devan']
['Neil Nitin Mukesh']
['Shakti Kapoor']
['Amit Sadh']
['Sunny Deol']
['Rahul Bagga']
['Sunny Deol']
['Amyra Dastur']
['Shah Rukh Khan']
['Ranveer Singh']
['Salman Khan']
['Ajay Devgn']
['Varun Dhawan']
['Shraddha Kapoor']
['Sunil Grover']
['Hrithik Roshan']
['Raj Arjun']
['Aamir Khan']
['Gurmeet Ram Rahim Singh']
['Arsh Bajwa']
['Rana Daggubati']
['Naseeruddin Shah']
['Kangana Ranaut']
['Nana Patekar']
['Arbaaz Khan']
['Varun Dhawan']
['Rajkummar Rao']
['Govinda']
['Rajat Kapoor']
['Anushka Sharma']
['Kiara Advani']
['Shaurya Singh']
['Pankaj Tripathi']
['Taapsee Pannu']
['Adil Hussain']
['Amitabh Bachchan']
['Sunny Leone']
['Hema Malini']
['Raveena Tandon']
['Amitabh Bachchan']
['Amardeep Insan']
['Shraddha Kapoor']
['Ayushmann Khurrana']
['Sachin Tendulkar']
['Irrfan Khan']
['Himansh Kohli']
['Adil Hussain']
['Jayesh Raj']
['Manisha Koirala']
['Deepika Padukone']
['Rajkummar Rao']
['Salman Khan']
['Riteish Deshmukh']
['Shiv Darshan']
['Ranbir Kapoor']
['Ashish Bisht']
['Aahana Kumra']
['Manoj Babani']
['Rajveer Ankur Singh']
['Kirti Kulhari']
['Shah Rukh Khan']
['Tiger Shroff']
['Akshay Kumar']
['Anil Kapoor']
['Kartik Aaryan']
['Ayushmann Khurrana']
['Nawazuddin Siddiqui']
['Prisha Aneja']
['Aadar Jain']
['Ayushmann Khurrana']
['Kunal Kapoor']
['Arjun Rampal']
['Kangana Ranaut']
['Farhan Akhtar']
['Sidharth Malhotra']
['Hugh Bonneville']
['Rishi Kapoor']
['Rajkummar Rao']
['Kunaal Roy Kapur']
['Sunny Leone']
['Shraddha Kapoor']
['Rina Charaniya']
['Nawazuddin Siddiqui']
['Sunny Deol']
['Sridevi']
['Saif Ali Khan']
['Soundarya Sharma']
['Sudha Chandran']
['Manoj Bajpayee']
['Zaira Wasim']
['Prakash Belawadi']
['Kalki Koechlin']
['Rajkummar Rao']
['Richa Chadha']
['Irrfan Khan']
['Zareen Khan']
['Nayna Bandhopadhyay']
['Vidya Balan']
['Nishikant Kamat']
['Sanjay Mishra']
['Kapil Sharma']
['Pulkit Samrat']
['Vijay Varma']
['Sushama Deshpande']
['Richa Chadha']
['Prince Shah']
['Tanima Bhattacharya']
['Akshay Kumar']
['Zeenat Aman']
['Madhavan']
['Tusshar Kapoor']
['Tusshar Kapoor']
['Himansh Kohli']
['Sadhana Singh']
['Sunny Deol']
['Aditya Roy Kapoor']
['Rishi Kapoor']
['Rajniesh Duggall']
['Krishna Chaturvedi']
['Girish Taurani']
['Sonam Kapoor']
['Sukhesh Arora']
['Raima Sen']
['Anuj Sachdeva']
['Parthaa Akerkar']
['Priyanka Chopra']
['Sidharth Malhotra']
['John Abraham']
['Patralekhaa Paul']
['Shah Rukh Khan']
['Swara Bhaskar']
['Randeep Hooda']
['Shraddha Kapoor']
['Pankaj Tripathi']
['Jimmy Sheirgill']
['Kartik Elangovan']
['Boman Irani']
['Manoj Bajpayee']
['Sharman Joshi']
['Emraan Hashmi']
['Aanchal Dwivedi']
['Sanjay Singh']
['Arvind Swamy']
['Radhika Apte']
['Randeep Hooda']
['Sachiin Joshi']
['Kajal Aggarwal']
['Amitabh Bachchan']
['Shahid Kapoor']
['Hazel Croney']
['V. Ravichandran']
['Vipin Sharma']
['Nawazuddin Siddiqui']
['Pulkit Samrat']
['Tannishtha Chatterjee']
['Krrish Chhabria']
['Avinash Dhyani']
['Zeenat Aman']
['Salman Khan']
['Shashank Arora']
['Urvashi Rautela']
['Naseeruddin Shah']
['Sara Loren']
['Tom Alter']
['Irrfan Khan']
['John Abraham']
['Rajeev Khandelwal']
["Ileana D'Cruz"]
['Sahil Anand']
['Hrithik Roshan']
['Diana Penty']
['Niharica Raizada']
['Tiger Shroff']
['Sidharth Malhotra']
['Nawazuddin Siddiqui']
['Emraan Hashmi']
['Taapsee Pannu']
['Tannishtha Chatterjee']
['Riteish Deshmukh']
['Yash Soni']
['Shreyas Talpade']
['Vinay Pathak']
['Jimmy Sharma']
['Sushant Singh Rajput']
['Ashok Insan']
['RJ Balaji']
['Saurav Chakraborty']
['Shashank Udapurkar']
['Shubham']
['Manoj Bajpayee']
['Sunny Leone']
['Aashish Bhatt']
['Ajay Devgn']
['Ronit Roy']
['Ranbir Kapoor']
['Neha Sharma']
['Farhan Akhtar']
['John Abraham']
['Alia Bhatt']
['Vaani Kapoor']
['Neha Dhupia']
['Jimmy Sheirgill']
['Sonarika Bhadoria']
['Amitabh Bachchan']
['Sharman Joshi']
['Aamir Khan']
['Harshvardhan Kapoor']
['Salman Khan']
['Kangana Ranaut']
['Kangana Ranaut']
['Soha Ali Khan']
['Prabhu Deva']
['Shah Rukh Khan']
['Salman Khan']
['Ranveer Singh']
['Anil Kapoor']
['Akshay Kumar']
['Akshay Kumar']
['Akshay Kumar']
['Akshay Kumar']
['Shakti Kapoor']
['Bipasha Basu']
['Arjun Kapoor']
['Zayed Khan']
['Malaika Arora']
['Naman Jain']
['Gurmeet Choudhary']
['Kay Kay Menon']
['Rati Agnihotri']
['Amitabh Bachchan']
['Arjun Rampal']
['Varun Dhawan']
['Swanand Kirkire']
['Sulabha Arya']
['Irrfan Khan']
['Nana Patekar']
['Ayushmann Khurrana']
['Anupam Kher']
['Gurmeet Ram Rahim Singh']
['Sidhant Gupta']
['Arjun Mathur']
['Ganesh Acharya']
['Anushka Sharma']
['Gulshan Devaiah']
['Sushant Singh Rajput']
['Adhyayan Suman']
['Vira Sathidar']
['Kalki Koechlin']
['Sunny Leone']
['Sara Loren']
['Emraan Hashmi']
['Auroshika Dey']
['Ira Dubey']
['Naseeruddin Shah']
['Vinay Pathak']
['Ram Kapoor']
['Deepika Padukone']
['Ranbir Kapoor']
['Shakti Anand']
['Anil Kapoor']
['Arshad Warsi']
['Meenakshi Dixit']
['Yash Acharya']
['Rajkummar Rao']
['Rahul Bagga']
['Mohit Baghel']
['Rishi Verma']
['Mimoh Chakraborty']
['Swara Bhaskar']
['Richa Chadha']
['Arshad Warsi']
['Mugdha Godse']
['Yashpal Sharma']
['Dharmendra']
['Sunny Deol']
['Smitha Gondkar']
['Kunal Kapoor']
['Ajay Devgn']
['Jacqueline Fernandez']
['Rishi Kapoor']
['Akshay Kumar']
['Vinay Pathak']
['Nawazuddin Siddiqui']
['Bhavita Anand']
['Saif Ali Khan']
['Suraj Pancholi']
['Shamim Khan']
['Irrfan Khan']
['Suhaas Ahuja']
['Jaideep Ahlawat']
['Charanpreet Insan']
['Akanksha Puri']
['Kunal Khemu']
['Aishwarya Rai Bachchan']
['Seema Azmi']
['Parveen Kaur']
['Kapil Sharma']
['Kartik Aaryan']
['Diganth']
['Shahid Kapoor']
['Nawazuddin Siddiqui']
['Kunal Khemu']
['Mann Bagga']
['Manish Paul']
['Sanjeev Kumar']
['Madhuri Dixit']
['Shiv Darshan']
['Gopi Desai']
['Mohinder Gujral']
['Zeenat Aman']
['Ranveer Singh']
['Salman Khan']
['Sidharth Malhotra']
['Adhyayan Suman']
['Indrapal Ahuja']
['Jimmy Sheirgill']
['Abhay Deol']
['Sahil Anand']
['Alia Bhatt']
['Sampat Pal Devi']
['Farhan Akhtar']
['Madhuri Dixit']
['Kangana Ranaut']
['Ayushmann Khurrana']
['Ali Zafar']
['Mahek Chahal']
['Monali Thakur']
['Sunny Leone']
['Harman Baweja']
['Sanjay Mishra']
['Sharman Joshi']
['Sachin Khedekar']
['Leeza Mangaldas']
['Pulkit Samrat']
['Zara Sheikh']
['Arjun Kapoor']
['Purab Kohli']
['Amitabh Bachchan']
['Varun Dhawan']
['Arvinder Bhatti']
['Kanika Batra']
['Jackky Bhagnani']
['Rajeev Khandelwal']
['Tanuj Virwani']
['Vijay Raaz']
['Kannan Arunachalam']
['Anjori Alagh']
['Satish Kaushik']
['Rahul Bagga']
['Himesh Reshammiya']
['Farooq Shaikh']
['Makrand Deshpande']
['Eesha Agarwal']
['Siddharth Gupta']
['Tiger Shroff']
['Rajkummar Rao']
['Sharib Hashmi']
['Kangana Ranaut']
['Kartik Aaryan']
['Swara Bhaskar']
['Simer Motiani']
['Anshuman Jha']
['Sidharth Malhotra']
['Vidya Balan']
['Saif Ali Khan']
['Varun Dhawan']
['Jay Bhanushali']
['Armaan Jain']
['Rajesh Khanna']
['Vir Das']
['Akshay Kumar']
['Jimmy Sheirgill']
['Reshmi Ghosh']
['Akshay Oberoi']
['Akshay Kumar']
['Anupam Kher']
['Rani Mukerji']
['Emraan Hashmi']
['Priyanka Chopra']
['Bipasha Basu']
['Deepika Padukone']
['Sonam Kapoor']
['Salil Acharya']
['Salman Khan']
['Saahil Prem']
['Alieesa P Badresia']
['Manoj Amarnani']
['Sasha Aagha']
['Tabu']
['Hrithik Roshan']
['Rati Agnihotri']
['Aditya Roy Kapoor']
['Asrani']
['Harshvardhan Deo']
['Nikhil Dwivedi']
['Karanvir Bohra']
['Puru Chibber']
['Soha Ali Khan']
['Rhea Chakraborty']
['Shah Rukh Khan']
['Rekha']
['Anupam Kher']
['Randeep Hooda']
['Akshay Kumar']
['Aadil Chahal']
['Shabana Azmi']
['Dimple Kapadia']
['Nishant Dahiya']
['Ranveer Singh']
['Emraan Hashmi']
['Saif Ali Khan']
['Vinod Acharya']
['Mannara Chopra']
['Prabhas']
['Mischa Barton']
['Shiv Panditt']
['Annu Kapoor']
['Barun Sobti']
['Rahul Bhat']
['Aamir Khan']
['Adhyayan Suman']
['Imran Khan']
['Naveen Kasturia']
['Arjun Rampal']
['Sarita Joshi']
['Kartik Aaryan']
['Juhi Chawla']
['Saif Ali Khan']
['Manisha Kelkar']
['Farooq Shaikh']
['Akshay Kumar']
['Randeep Hooda']
['Vivek Oberoi']
['Rajkummar Rao']
['Akash']
['Vishwa Mohan Badola']
['Neil Nitin Mukesh']
['Saqib Saleem']
['Arshad Warsi']
['Jimmy Sheirgill']
['Asha Bhosle']
['Kamal Haasan']
['Jackky Bhagnani']
['Aditya Roy Kapoor']
['Emraan Hashmi']
['Ajay Devgn']
['Ayushmann Khurrana']
['Vivek Oberoi']
['Vidyut Jammwal']
['Rani Mukerji']
['Saif Ali Khan']
['Riya Vij']
['Arjun Kapoor']
['Preity Zinta']
['Veena Malik']
['Ranbir Kapoor']
['Pulkit Samrat']
['Rupa Bhimani']
['Dhanush']
['Kay Kay Menon']
['Neil Nitin Mukesh']
['Vidya Balan']
['Anupam Kher']
['Sanjay Dutt']
['Farhan Akhtar']
['Wamiqa Gabbi']
['Shadab Kamal']
['Sunil Shetty']
['Prateik']
['Tusshar Kapoor']
['Tanuj Virwani']
['Poonam Pandey']
['Deepak Dobriyal']
['Hemant Gopal']
['Joy Mukherjee']
['Rishi Kapoor']
['Rajesh Tailang']
['Akshay Kumar']
['John Abraham']
['Amitabh Bachchan']
['Sushant Singh Rajput']
['Shruti Haasan']
['Deepika Padukone']
['Vivek Oberoi']
['Naseeruddin Shah']
['Karan Kundrra']
['Shahid Kapoor']
['Aida Elkashef']
['Irrfan Khan']
['Anisa Butt']
['Akshay Kumar']
['Rajkummar Rao']
['Manish Paul']
['Puneet Singh Ratn']
['Kangana Ranaut']
['Sumit Nijhawan']
['Tinnu Anand']
['Chandan Roy Sanyal']
['Elisha Kriis']
['Ashmit Patel']
['Imran Khan']
['Manu Rishi Chadha']
['Naseeruddin Shah']
['Paresh Rawal']
['Saif Ali Khan']
['Aamir Khan']
['Ali Zafar']
['Ranveer Singh']
['Sharman Joshi']
['Naseeruddin Shah']
['Shiney Ahuja']
['Karan Sharma']
['Sunny Deol']
['Ranveer Singh']
['Hrithik Roshan']
['Kareena Kapoor']
['Prateik']
['Kiran Bhatia']
['Bipasha Basu']
['Riteish Deshmukh']
['Jahangir Khan']
['Irrfan Khan']
['Vidya Balan']
['Mithun Chakraborty']
['Kareena Kapoor']
['Manish Chaudhary']
['Kavin Dave']
['Shikhi Gupta']
['Archana Joglekar']
['Tusshar Kapoor']
['Pulkit Samrat']
['Ayushmann Khurrana']
['Nikhil Dwivedi']
['Anil Kapoor']
['Karisma Kapoor']
['Arjun Kapoor']
['Sanjay Dutt']
['Gul Panag']
['Yudhveer Bakoliya']
['Kay Kay Menon']
['Emraan Hashmi']
['Sharman Joshi']
['Shahid Kapoor']
['Anupam Kher']
['Anya Anand']
['Julia Datt']
['Manoj Bajpayee']
['Manoj Bajpayee']
['Saif Ali Khan']
['Naresh Sharma']
['Riteish Deshmukh']
['Sonu Sood']
['Nassar Abdulla']
['Salman Khan']
['Vickrant Mahajan']
['Freny Bhagat']
['Akshay Kumar']
['Omkar Das Manikpuri']
['Sunil Shetty']
['Manoj Bajpayee']
['Bidita Bag']
['Harish Chabbra']
['Ranbir Kapoor']
['Kareena Kapoor']
['Sagar Bhangade']
['Vivek Oberoi']
['Ravi Kishan']
['Paresh Rawal']
['Rani Mukerji']
['Manoj Bajpayee']
['J.D. Chakravarthi']
['Cary Elwes']
['Arjun Rampal']
['Alia Bhatt']
['Jackky Bhagnani']
['Emraan Hashmi']
['Vicky Ahuja']
['Sunidhi Chauhan']
['Asrani']
['Shah Rukh Khan']
['Aamir Khan']
['Himanshu Bhatt']
['Ajay Devgn']
['Ashok Banthia']
['Salman Khan']
['Vinod Khanna']
['Akshay Kumar']
['Amitabh Bachchan']
['Sridevi']
['Vivek Sudershan']
['Nafisa Ali']
['Mohsin']
['Prateik']
['Gul Panag']
['Vatsal Sheth']
['Ajay Devgn']
['Russell Geoffrey Banks']
['Vinay Pathak']
['Rishi Kapoor']
['Priyanka Chopra']
['Madhavan']
['Arshad Warsi']
['Deepti Naval']
['Akshay Kumar']
['Sumit Arora']
['Anay']
['Om Puri']
['Abhishek Bachchan']
['Sendhil Ramamurthy']
['Darsheel Safary']
['Vinay Pathak']
['Ishaan Manhaas']
['Sanjay Mishra']
['Ashutosh Rana']
['Juhi Chawla']
['Govinda']
['Mimoh Chakraborty']
['Tusshar Kapoor']
['Kainaz Motivala']
['Partho A. Gupte']
['Nana Patekar']
['Sara Arjun']
['Kalki Koechlin']
['Kartik Aaryan']
['Vinay Pathak']
['Lillete Dubey']
['Sanjay Dutt']
['Amitabh Bachchan']
['Imran Khan']
['Emraan Hashmi']
['Aarav Khanna']
['Hrithik Roshan']
['Raghuvir Yadav']
['Gulshan Grover']
['Naushaad Abbas']
['Shefali Shah']
['Ajay Devgn']
['Rahul Jaiswal']
['Apoorva Arora']
['Isha Koppikar']
['Rajniesh Duggall']
['Amitabh Bachchan']
['Sanjay Dutt']
['Anupam Kher']
['Salman Khan']
['Deepshika Nagpal']
['Deepak Dobriyal']
['Tusshar Kapoor']
['Kiron Kher']
['Imran Khan']
['Shahid Kapoor']
['Mikaal']
['John Abraham']
['Jimmy Sheirgill']
['Vinay Pathak']
['Vinay Virmani']
['Dev Anand']
['Zayed Khan']
['Saqib Saleem']
['Sachiin Joshi']
['Shah Rukh Khan']
['Ranbir Kapoor']
['Chirag Paswan']
['Dharmendra']
['Himesh Reshammiya']
['Ranveer Singh']
['Akshay Kumar']
['Abhishek Bachchan']
['Rani Mukerji']
['Ajay Devgn']
['Vidya Balan']
['Priyanka Chopra']
['Shahid Kapoor']
['Prateik']
['Salman Khan']
['Siddharth']
['Amitabh Bachchan']
['Vidya Balan']
['Paresh Rawal']
['Sunny Gill']
['Shreyas Talpade']
['Tabu']
['Shah Rukh Khan']
['Amitabh Bachchan']
['Siddhartha Gupta']
['Shah Rukh Khan']
['Tanushree Dutta']
['Paul Sidhu']
['Sunny Deol']
['Gurdas Maan']
['Master Shams']
['Om Puri']
['Vikrum Kumar']
['Aditya Narayan']
['Arshad Warsi']
['Boman Irani']
['Nana Patekar']
['Priyanka Chopra']
['Arbaaz Khan']
['Rekha']
['Rahul Bose']
['Nana Patekar']
['Sudeep']
['Farooq Shaikh']
['Rohit Roy']
['Sachin Khedekar']
['Anuj Saxena']
['Akshay Kumar']
['Hazel Croney']
['Sanjeev Bhaskar']
['Vivek Oberoi']
['Abhishek Bachchan']
['Atul Kulkarni']
['Rajpal Yadav']
['Hrithik Roshan']
['Nushrat Bharucha']
['Kareena Kapoor']
['Bhushan Agarwal']
['Prashant Narayanan']
['Sanjay Dutt']
['Akshay Kumar']
['Ali Zafar']
['Rajat Barmecha']
['Ajay Devgn']
['Bobby Deol']
['Omkar Das Manikpuri']
['Neil Nitin Mukesh']
['Gul Panag']
['Raj Singh Chaudhary']
['John Abraham']
['Barkha Madan']
['Salman Khan']
['Supriya Pathak']
['Sunil Shetty']
['Rituparna Sengupta']
['Ranvir Shorey']
['Mallika Sherawat']
['Emraan Hashmi']
['Rishi Kapoor']
['Ajay Devgn']
['Manoj Bajpayee']
['Sanjay Dutt']
['John Abraham']
['Hrithik Roshan']
['Varun Bhagwat']
['Deepika Padukone']
['Sunny Deol']
['Rajat Kapoor']
['Akanksha']
['Jimmy Sheirgill']
['Sanjay Dutt']
['Ranveer Singh']
['Aditya Srivastava']
['Arunoday Singh']
['Akshay Kumar']
['Akshay Oberoi']
['Ajay Devgn']
['Neil Nitin Mukesh']
['Sahil Khan']
['Imran Khan']
['Sushmita Sen']
['Priyanka Chopra']
['Zeenat Aman']
['Bipasha Basu']
['Akshay Kumar']
['Aamir Khan']
['Farhan Akhtar']
['Saif Ali Khan']
['Salman Khan']
['Waheeda Rehman']
['Kangana Ranaut']
['Hrishitaa Bhatt']
['Ranbir Kapoor']
['Asrani']
['Irrfan Khan']
['Kay Kay Menon']
['Arshad Warsi']
['Paresh Rawal']
['Rati Agnihotri']
['Harman Baweja']
['Shahid Kapoor']
['Fardeen Khan']
['John Abraham']
['Kay Kay Menon']
['Aftab Shivdasani']
['Naseeruddin Shah']
['Inaamulhaq']
['Neil Nitin Mukesh']
['Kunal Khemu']
['Bobby Deol']
['Anita']
['Parzaan Dastur']
['Meghan Jadhav']
['Shreyas Talpade']
['John Abraham']
['Kay Kay Menon']
['Sanjay Dutt']
['Mithun Chakraborty']
['Govinda']
['Sunil Shetty']
['Jackie Shroff']
['Anupam Kher']
['Shreyas Talpade']
['Rishi Kapoor']
['Rajendra Prasad']
['Arjun Rampal']
['Mithun Chakraborty']
['Mithun Chakraborty']
['Bobby Deol']
['Shahid Kapoor']
['Harman Baweja']
['Fardeen Khan']
['Sanjay Dutt']
['Ranbir Kapoor']
['Salman Khan']
['Akshay Kumar']
['Atmaram Bhende']
['Amitabh Bachchan']
['Salman Khan']
['Manoj Bajpayee']
['Emraan Hashmi']
['Lewis Tan']
['Akshay Kumar']
['Amitabh Bachchan']
['Ranbir Kapoor']
['Aamir Bashir']
['Farooq Shaikh']
['Mithun Chakraborty']
['Abhishek Bachchan']
['Saif Ali Khan']
['Shah Rukh Khan']
['Aamir Khan']
['Akshay Kumar']
['Ajay Devgn']
['Hrithik Roshan']
['Ranbir Kapoor']
['Amitabh Bachchan']
['Amitabh Bachchan']
['Ajay Devgn']
['Omkar Bhatkar']
['Shreyas Talpade']
['Manisha Koirala']
['Ajay Devgn']
['Tusshar Kapoor']
['Juhi Chawla']
['Ajay Devgn']
['Kay Kay Menon']
['Akshay Kumar']
['Dino Morea']
['Mimoh Chakraborty']
['Emraan Hashmi']
['Mithun Chakraborty']
['Sikander Kher']
['Paresh Rawal']
['Ahraz Ahmed']
['Aftab Shivdasani']
['Amita Pathak']
['Saahil Chadha']
['Saif Ali Khan']
['Kay Kay Menon']
['Shahid Kapoor']
['Harman Baweja']
['Adhvik Mahajan']
['Vivek Oberoi']
['Govinda']
['Amitabh Bachchan']
['Paresh Rawal']
['Mallika Sherawat']
['Arjun Rampal']
['Tusshar Kapoor']
['Bobby Deol']
['Sammir Dattani']
['Victor Banerjee']
['Rajniesh Duggall']
['Amitabh Bachchan']
['Shreyas Talpade']
['Kiron Kher']
['Jackie Shroff']
['Jayshree Arora']
['Sharman Joshi']
['Himesh Reshammiya']
['Sohail Khan']
['Saif Ali Khan']
['Isha Koppikar']
['Kamal Rashid Khan']
['Priyanka Chopra']
['Vinay Pathak']
['Salman Khan']
['Abhay Deol']
['Vinay Pathak']
['Shabana Azmi']
['Manoj Bajpayee']
['Anupam Kher']
['Rajesh Khanna']
['Dino Morea']
['Irrfan Khan']
['Amitabh Bachchan']
['Himesh Reshammiya']
['Tusshar Kapoor']
['Nauheed Cyrusi']
['Madhuri Dixit']
['Dharmendra']
['Emraan Hashmi']
['Vinay Pathak']
['Akshay Kumar']
['Dino Morea']
['Sunny Deol']
['Mouli Ganguly']
['Krishna Abhishek']
['Irrfan Khan']
['Kay Kay Menon']
['Pankaj Kapur']
['Jazzy Doe']
['Mona Ambegaonkar']
['Ajay Devgn']
['Amitabh Bachchan']
['Jimmy Sheirgill']
['Fardeen Khan']
['Shah Rukh Khan']
['Sanjay Dutt']
['John Abraham']
['Pankaj Kapur']
['Sunil Pal']
['Muzamil Ibrahim']
['Imaaduddin Shah']
['Sharman Joshi']
['Abhay Deol']
['Arjun Rampal']
['Akshaye Khanna']
['Rishi Kapoor']
['Arbaaz Khan']
['Amitabh Bachchan']
['Gautam Gupta']
['Mohan Azaad']
['Juanna Sanghvi']
['Mithun Chakraborty']
['Ranvir Shorey']
['Govinda']
['Abhishek Bachchan']
['Shahid Kapoor']
['Tusshar Kapoor']
['Shahid Kapoor']
['Shiney Ahuja']
['Dharmendra']
['Fardeen Khan']
['Tusshar Kapoor']
['Rekha']
['Jimmy Sheirgill']
['Rani Mukerji']
['Dharmendra']
['Shabana Azmi']
['Abhay Deol']
['Salman Khan']
['Menekka Arora']
['Nana Patekar']
['Bobby Deol']
['Linda Arsenio']
['Kal Penn']
['Akshay Kumar']
['Jason Lewis']
['Sanjay Dutt']
['Amitabh Bachchan']
['John Abraham']
['Shah Rukh Khan']
['Salman Khan']
['Rahul Khanna']

In [170]:
# arithematic operator (broadcasting)

print(100 - custom)

maths      33
science    31
english     1
french     90
sst         0
dtype: int64

In [171]:
# Relational operators
print(vk >=50 )

           runs
match_no
8         False
87        False
93        False
91        False
206       False
...         ...
164        True
120        True
123        True
126        True
128        True

[215 rows x 1 columns]

##Boolean Indexing on Series

In [172]:
# find no. of 50's and 100's scored
print(vk[vk>=50].dropna().size)

50

In [173]:
# find number of ducks
print(vk[vk==0].dropna().size)

9

In [174]:
# count number of days when more than 200 subs are gained
print(subs[subs['Subscribers gained'] > 200].size)

59

In [179]:
# how many has made more than 20 movies
num_movies = movies.value_counts()
print(num_movies[num_movies > 20])

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64

##Plotting Graphs on Series