#Pandas All Concepts

In [21]:
# importing pandas
import numpy as np
import pandas as pd

##Series made from Lists

In [22]:
# Series -> columns in the table are called series in pandas. Series is a class inside pandas.
country = ['India','Pakistan','China','Srilanka']
pd.Series(country)

# Notes: In pandas , when we get dtype: object , it means values are in string form. Not in everycase but most of the cases.
#        Series include two things: index and values
#        country is as object of 'Series' class

0       India
1    Pakistan
2       China
3    Srilanka
dtype: object

In [23]:
# integers
runs = [13,45,77,23,55]
pd.Series(runs)

0    13
1    45
2    77
3    23
4    55
dtype: int64

In [34]:
# custom index
marks = [67,69,99,10]
subjects = ['maths','science','english','french']

custom = pd.Series(marks,index=subjects)
print(custom)

maths      67
science    69
english    99
french     10
dtype: int64

In [36]:
# setting a name
y = pd.Series(marks,index=subjects,name='Marks of Mayank')
print(y)

maths      67
science    69
english    99
french     10
Name: Marks of Mayank, dtype: int64

##Series made from dictionary

In [37]:
marks = {
    'English':69,
    'Hindi':100,
    'Computer science':100
}

marks_dict = pd.Series(marks)
print(marks_dict)

English              69
Hindi               100
Computer science    100
dtype: int64

##Series Attributes

In [38]:
# size
marks_dict.size

3

In [39]:
y.size

4

In [40]:
# dtype
y.dtype

dtype('int64')

In [42]:
# name
y.name

'Marks of Mayank'

In [43]:
# is_unique -> tells about all the elements of the series are unique of not
y.is_unique

True

In [44]:
# index
y.index

Index(['maths', 'science', 'english', 'french'], dtype='object')

In [46]:
runs = pd.Series([13,45,77,23,55])
runs.index

# RangeIndex is just a special kind of object which store index values

RangeIndex(start=0, stop=5, step=1)

In [49]:
# values -> gives a numpy array
y.values

array([67, 69, 99, 10])

##Series using read_csv

In [59]:
# with 1 column
print(pd.read_csv('/content/subs.csv'))

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [69]:
from numpy._core.fromnumeric import squeeze
# with 2 column
print(pd.read_csv('/content/kohli_ipl.csv',index_col='match_no'))

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [73]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie')
print(movies)

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]