#Pandas All Concepts

In [2]:
# importing pandas
import numpy as np
import pandas as pd

##Series made from Lists

In [3]:
# Series -> columns in the table are called series in pandas. Series is a class inside pandas.
country = ['India','Pakistan','China','Srilanka']
pd.Series(country)

# Notes: In pandas , when we get dtype: object , it means values are in string form. Not in everycase but most of the cases.
#        Series include two things: index and values
#        country is as object of 'Series' class

0       India
1    Pakistan
2       China
3    Srilanka
dtype: object

In [4]:
# integers
runs = [13,45,77,23,55]
pd.Series(runs)

0    13
1    45
2    77
3    23
4    55
dtype: int64

In [5]:
# custom index
marks = [67,69,99,10]
subjects = ['maths','science','english','french']

custom = pd.Series(marks,index=subjects)
print(custom)

maths      67
science    69
english    99
french     10
dtype: int64

In [6]:
# setting a name
y = pd.Series(marks,index=subjects,name='Marks of Mayank')
print(y)

maths      67
science    69
english    99
french     10
Name: Marks of Mayank, dtype: int64

##Series made from dictionary

In [7]:
marks = {
    'English':69,
    'Hindi':100,
    'Computer science':100
}

marks_dict = pd.Series(marks)
print(marks_dict)

English              69
Hindi               100
Computer science    100
dtype: int64

##Series Attributes

In [8]:
# size
marks_dict.size

3

In [9]:
y.size

4

In [10]:
# dtype
y.dtype

dtype('int64')

In [11]:
# name
y.name

'Marks of Mayank'

In [12]:
# is_unique -> tells about all the elements of the series are unique of not
y.is_unique

True

In [13]:
# index
y.index

Index(['maths', 'science', 'english', 'french'], dtype='object')

In [14]:
runs = pd.Series([13,45,77,23,55])
runs.index

# RangeIndex is just a special kind of object which store index values

RangeIndex(start=0, stop=5, step=1)

In [15]:
# values -> gives a numpy array
y.values

array([67, 69, 99, 10])

##Series using read_csv

In [16]:
# with 1 column
subs = pd.read_csv('/content/subs.csv')
print(subs)

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [17]:
# with 2 column
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')
print(vk)

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [18]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie')
print(movies)

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

##Series Methods

In [19]:
# head and tail
# head -> give data preview only , show first 5 rows from data by dafault BUT we can ask for more by mentioning no. of rows in head()

print(subs.head())

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [20]:
print(vk.tail())

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [21]:
# sample -> give one row from data randomly
# useful when our data has some bias
print(movies.sample(3))

                                   lead
movie
Hume Tumse Pyaar Kitna   Karanvir Bohra
Click (2010 film)       Shreyas Talpade
Ab Tak Chhappan 2          Nana Patekar

In [22]:
# value_counts -> tells the frequency for a value present in data in DESC order
print(movies.value_counts())

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Naveen Bawa          1
Naushaad Abbas       1
Nauheed Cyrusi       1
Natalia Janoszek     1
Nishikant Kamat      1
Name: count, Length: 566, dtype: int64

In [23]:
# sort_values
print(vk.sort_values(by='runs',ascending=False))

          runs
match_no
128        113
126        109
123        108
120        100
164        100
...        ...
93           0
130          0
206          0
207          0
211          0

[215 rows x 1 columns]

In [24]:
# we can use head() here also
# THIS IS CALLED METHOD CHAINING
print(vk.sort_values(by='runs',ascending=False).head(3).values[0])

[113]

In [25]:
# if you want to do permanent changes in dataset , you have to use inplace=True
vk.sort_values(by='runs',inplace=True)

In [26]:
print(vk)

          runs
match_no
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [27]:
# sort_index
print(movies.sort_index())

                                        lead
movie
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Arjun Kapoor
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

##Series Maths Methods

In [28]:
# count -> give count of elements but dont consider missing values
# size -> do same work but consider missing values

print(vk.count())
print()
print(vk.size)

runs    215
dtype: int64

215

In [29]:
# sum
print(subs.sum())

Subscribers gained    49510
dtype: int64

In [30]:
# product
print(subs.product())

Subscribers gained    0
dtype: int64

In [31]:
# mean
print(subs.mean())

Subscribers gained    135.643836
dtype: float64

In [32]:
# median
print(vk.median())

runs    24.0
dtype: float64

In [33]:
# mode -> which value has highest frequency
print(movies.mode())

           lead
0  Akshay Kumar

In [34]:
# std (standard deviation)
print(subs.std())

Subscribers gained    62.675023
dtype: float64

In [35]:
# var (variance)
print(vk.var())

runs    688.002478
dtype: float64

In [36]:
# min/max
print(subs.min())

Subscribers gained    33
dtype: int64

In [37]:
# describe -> give summary
print(vk.describe())

             runs
count  215.000000
mean    30.855814
std     26.229801
min      0.000000
25%      9.000000
50%     24.000000
75%     48.000000
max    113.000000

##Series Indexing

In [38]:
# integer indexing
x = pd.Series([12,13,14,35,77,2,1,9])
x[0]

np.int64(12)

In [39]:
# negative indexing series
# DOES NOT WORKS

In [40]:
# fetching value from giving index
print(movies.iloc[0])

lead    Vicky Kaushal
Name: Uri: The Surgical Strike, dtype: object

In [41]:
print(movies.iloc[-1])

lead    Akshay Kumar
Name: Awara Paagal Deewana, dtype: object

In [42]:
print(vk.iloc[0])

runs    0
Name: 8, dtype: int64

In [43]:
# Slicing
print(vk[5:16])

          runs
match_no
207          0
135          0
130          0
211          0
106          1
204          1
113          1
77           1
1            1
5            1
75           1

In [44]:
print(vk[-5:])

          runs
match_no
164        100
120        100
123        108
126        109
128        113

In [45]:
print(movies[-5:])

                                    lead
movie
Hum Tumhare Hain Sanam    Shah Rukh Khan
Aankhen (2002 film)     Amitabh Bachchan
Saathiya (film)             Vivek Oberoi
Company (film)                Ajay Devgn
Awara Paagal Deewana        Akshay Kumar

In [46]:
print(movies[::2])

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
The Accidental Prime Minister (film)       Anupam Kher
Evening Shadows                       Mona Ambegaonkar
Fraud Saiyaan                             Arshad Warsi
Manikarnika: The Queen of Jhansi        Kangana Ranaut
...                                                ...
Raaz (2002 film)                            Dino Morea
Waisa Bhi Hota Hai Part II                Arshad Warsi
Kaante                                Amitabh Bachchan
Aankhen (2002 film)                   Amitabh Bachchan
Company (film)                              Ajay Devgn

[750 rows x 1 columns]

In [47]:
# fancy indexing
print(vk.iloc[[1,3,4,5]])

          runs
match_no
87           0
91           0
206          0
207          0

In [48]:
# indexing with labels
print(movies.loc['The Accidental Prime Minister (film)'])

lead    Anupam Kher
Name: The Accidental Prime Minister (film), dtype: object

##Editing Series

In [49]:
# using indexing
custom

maths      67
science    69
english    99
french     10
dtype: int64

In [50]:
custom['sst'] = 100

In [51]:
print(custom)

maths       67
science     69
english     99
french      10
sst        100
dtype: int64

In [52]:
# slicing
runs[2:4] = [100,100]
print(runs)

0     13
1     45
2    100
3    100
4     55
dtype: int64

In [53]:
# fancy indexing
runs[[0,3,4]] = [0,0,0]

In [54]:
print(runs)

0      0
1     45
2    100
3      0
4      0
dtype: int64

In [55]:
# using index label
movies['2 States (2014 film)'] = 'Alia Bhatt'

In [56]:
print(movies.loc['2 States (2014 film)'])

lead                    Arjun Kapoor
2 States (2014 film)      Alia Bhatt
Name: 2 States (2014 film), dtype: object

##Series with python functionalities

In [58]:
# len/type/dir/sorted/min/max
print(len(subs))
print(type(subs))

365
<class 'pandas.core.frame.DataFrame'>

In [60]:
# dir -> show all attributes applicable
print(dir(subs))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_arith_method_with_reindex', '_as_manager', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_create_data_for_split_and_tight_to_dict', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item_cache', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_nocopy', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_copy', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_item_cache', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [71]:
print(sorted(subs))

['Subscribers gained']

In [72]:
# sorted -> sort plus give output in list format
print(subs['Subscribers gained'].sort_values().to_list())

[33, 33, 35, 37, 39, 40, 40, 40, 40, 42, 42, 43, 44, 44, 44, 45, 46, 46, 48, 49, 49, 49, 49, 50, 50, 50, 51, 54, 56, 56, 56, 56, 57, 61, 62, 64, 65, 65, 66, 66, 66, 66, 67, 68, 70, 70, 70, 71, 71, 72, 72, 72, 72, 72, 73, 74, 74, 75, 76, 76, 76, 76, 77, 77, 78, 78, 78, 79, 79, 80, 80, 80, 81, 81, 82, 82, 83, 83, 83, 84, 84, 84, 85, 86, 86, 86, 87, 87, 87, 87, 88, 88, 88, 88, 88, 89, 89, 89, 90, 90, 90, 90, 91, 92, 92, 92, 93, 93, 93, 93, 95, 95, 96, 96, 96, 96, 97, 97, 98, 98, 99, 99, 100, 100, 100, 101, 101, 101, 102, 102, 103, 103, 104, 104, 104, 105, 105, 105, 105, 105, 105, 105, 105, 105, 108, 108, 108, 108, 108, 108, 109, 109, 110, 110, 110, 111, 111, 112, 113, 113, 113, 114, 114, 114, 114, 115, 115, 115, 115, 117, 117, 117, 118, 118, 119, 119, 119, 119, 120, 122, 123, 123, 123, 123, 123, 124, 125, 126, 127, 128, 128, 129, 130, 131, 131, 132, 132, 134, 134, 134, 135, 135, 136, 136, 136, 137, 138, 138, 138, 139, 140, 144, 145, 146, 146, 146, 146, 147, 149, 150, 150, 150, 150, 151, 152, 152, 152, 153, 153, 153, 154, 154, 154, 155, 155, 156, 156, 156, 156, 157, 157, 157, 157, 158, 158, 159, 159, 160, 160, 160, 160, 162, 164, 166, 167, 167, 168, 170, 170, 170, 170, 171, 172, 172, 173, 173, 173, 174, 174, 175, 175, 176, 176, 177, 178, 179, 179, 180, 180, 180, 182, 183, 183, 183, 184, 184, 184, 185, 185, 185, 185, 186, 186, 186, 188, 189, 190, 190, 192, 192, 192, 196, 196, 196, 197, 197, 202, 202, 202, 203, 204, 206, 207, 209, 210, 210, 211, 212, 213, 214, 216, 219, 220, 221, 221, 222, 222, 224, 225, 225, 226, 227, 228, 229, 230, 231, 233, 236, 236, 237, 241, 243, 244, 245, 247, 249, 254, 254, 258, 259, 259, 261, 261, 265, 267, 268, 269, 276, 276, 290, 295, 301, 306, 312, 396]

In [74]:
print(subs['Subscribers gained'].min())

33

In [75]:
print(subs['Subscribers gained'].max())

396

In [76]:
# type conversion
list(custom)

[67, 69, 99, 10, 100]

In [77]:
dict(custom)

{'maths': np.int64(67),
 'science': np.int64(69),
 'english': np.int64(99),
 'french': np.int64(10),
 'sst': np.int64(100)}

In [83]:
# membership operator generally for indexes
'Why Cheat India' in movies.index

True

In [85]:
'Alia Bhatt' in movies.values

True

In [87]:
# looping -> use for values
for i in movies.values:
  print(i)

['Vicky Kaushal' 'Alia Bhatt']
['Vicky Ahuja' 'Alia Bhatt']
['Anupam Kher' 'Alia Bhatt']
['Emraan Hashmi' 'Alia Bhatt']
['Mona Ambegaonkar' 'Alia Bhatt']
['Geetika Vidya Ohlyan' 'Alia Bhatt']
['Arshad Warsi' 'Alia Bhatt']
['Radhika Apte' 'Alia Bhatt']
['Kangana Ranaut' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Ali Asgar' 'Alia Bhatt']
['Ranveer Singh' 'Alia Bhatt']
['Prit Kamani' 'Alia Bhatt']
['Ajay Devgn' 'Alia Bhatt']
['Sushant Singh Rajput' 'Alia Bhatt']
['Amitabh Bachchan' 'Alia Bhatt']
['Abhimanyu Dasani' 'Alia Bhatt']
['Talha Arshad Reshi' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Garima Agarwal' 'Alia Bhatt']
['Rasika Agashe' 'Alia Bhatt']
['Barun Sobti' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Zaheer Iqbal' 'Alia Bhatt']
['Vidyut Jammwal' 'Alia Bhatt']
['Deepika Amin' 'Alia Bhatt']
['Manav Kaul' 'Alia Bhatt']
['Naseeruddin Shah' 'Alia Bhatt']
['Varun Dhawan' 'Alia Bhatt']
['Shreyas Talpade' 'Alia Bhatt']
['Tiger Shroff' 'Alia Bhatt']
['Boman Irani' 'Alia Bhatt']
['Ajay Devgn' 'Alia Bhatt']
['Arjun Kapoor' 'Alia Bhatt']
['Gavie Chahal' 'Alia Bhatt']
['Prabhu Deva' 'Alia Bhatt']
['Shahid Kapoor' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Anupam Kher' 'Alia Bhatt']
['Karanvir Bohra' 'Alia Bhatt']
['Hrithik Roshan' 'Alia Bhatt']
['Jimmy Sheirgill' 'Alia Bhatt']
['John Abraham' 'Alia Bhatt']
['Rishi Kapoor' 'Alia Bhatt']
['Kangana Ranaut' 'Alia Bhatt']
['Natalia Janoszek' 'Alia Bhatt']
['Diljit Dosanjh' 'Alia Bhatt']
['Sidharth Malhotra' 'Alia Bhatt']
['Rajeev Khandelwal' 'Alia Bhatt']
['Zaira Wasim' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Jacqueline Fernandez' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Akshaye Khanna' 'Alia Bhatt']
['Sonam Kapoor' 'Alia Bhatt']
['Karan Deol' 'Alia Bhatt']
['Sanjay Dutt' 'Alia Bhatt']
['Bhavesh Kumar' 'Alia Bhatt']
['Sanaya Irani' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Siddhanth Kapoor' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Taapsee Pannu' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Sunny Singh Nijjar' 'Alia Bhatt']
['Neil Nitin Mukesh' 'Alia Bhatt']
['Suraj Pancholi' 'Alia Bhatt']
['Boman Irani' 'Alia Bhatt']
['Riteish Deshmukh' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Shahbaaz Khan' 'Alia Bhatt']
['Kriti Kharbanda' 'Alia Bhatt']
['Naseeruddin Shah' 'Alia Bhatt']
['Vardhan Puri' 'Alia Bhatt']
['Sushant Singh Rajput' 'Alia Bhatt']
['Kartik Aaryan' 'Alia Bhatt']
['Vidyut Jammwal' 'Alia Bhatt']
['Rani Mukerji' 'Alia Bhatt']
['Salman Khan' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Saif Ali Khan' 'Alia Bhatt']
['Kay Kay Menon' 'Alia Bhatt']
['Nora Fatehi' 'Alia Bhatt']
['Ashmit Patel' 'Alia Bhatt']
['Viineet Kumar' 'Alia Bhatt']
['Rahul Bhat' 'Alia Bhatt']
['Vicky Kaushal' 'Alia Bhatt']
['Sidharth Malhotra' 'Alia Bhatt']
['Deepika Padukone' 'Alia Bhatt']
['Geetanjali Thapa' 'Alia Bhatt']
['Akshay Anand' 'Alia Bhatt']
['Pulkit Samrat' 'Alia Bhatt']
['Kartik Aaryan' 'Alia Bhatt']
['Lee Byford' 'Alia Bhatt']
['Taapsee Pannu' 'Alia Bhatt']
['Aisha Ahmed' 'Alia Bhatt']
['Ajay Devgn' 'Alia Bhatt']
['Rani Mukerji' 'Alia Bhatt']
['Manoj Bajpayee' 'Alia Bhatt']
['Tiger Shroff' 'Alia Bhatt']
['Varun Dhawan' 'Alia Bhatt']
['Prabhu Deva' 'Alia Bhatt']
['Ishaan Khattar' 'Alia Bhatt']
['Abhay Deol' 'Alia Bhatt']
['Yogesh Raj Mishra' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Alia Bhatt' 'Alia Bhatt']
['Naseeruddin Shah' 'Alia Bhatt']
['Sumeet Vyas' 'Alia Bhatt']
['Vinay Pathak' 'Alia Bhatt']
['John Abraham' 'Alia Bhatt']
['Danny Denzongpa' 'Alia Bhatt']
['Harshvardhan Kapoor' 'Alia Bhatt']
['Jimmy Sheirgill' 'Alia Bhatt']
['Anil Kapoor' 'Alia Bhatt']
['Ishaan Khattar' 'Alia Bhatt']
['Ranbir Kapoor' 'Alia Bhatt']
['Sanjay Dutt' 'Alia Bhatt']
['Dharmesh Yelande' 'Alia Bhatt']
['Taapsee Pannu' 'Alia Bhatt']
['Arjun Mathur' 'Alia Bhatt']
['Irrfan Khan' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['John Abraham' 'Alia Bhatt']
['Sonakshi Sinha' 'Alia Bhatt']
['Utkarsh Sharma' 'Alia Bhatt']
['Dharmendra' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Jackie Shroff' 'Alia Bhatt']
['Avinash Tiwary' 'Alia Bhatt']
['Manoj Bajpayee' 'Alia Bhatt']
['Paoli Dam' 'Alia Bhatt']
['Sanya Malhotra' 'Alia Bhatt']
['Shahid Kapoor' 'Alia Bhatt']
['Abhishek Bharate' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Manish Anand' 'Alia Bhatt']
['Taapsee Pannu' 'Alia Bhatt']
['Jackky Bhagnani' 'Alia Bhatt']
['Anushka Sharma' 'Alia Bhatt']
['Radhika Apte' 'Alia Bhatt']
['Rhea Chakraborty' 'Alia Bhatt']
['Govinda' 'Alia Bhatt']
['Sohum Shah' 'Alia Bhatt']
['Kajol' 'Alia Bhatt']
['Arjun Kapoor' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Nargis Fakhri' 'Alia Bhatt']
['Aishwarya Devan' 'Alia Bhatt']
['Neil Nitin Mukesh' 'Alia Bhatt']
['Shakti Kapoor' 'Alia Bhatt']
['Amit Sadh' 'Alia Bhatt']
['Sunny Deol' 'Alia Bhatt']
['Rahul Bagga' 'Alia Bhatt']
['Sunny Deol' 'Alia Bhatt']
['Amyra Dastur' 'Alia Bhatt']
['Shah Rukh Khan' 'Alia Bhatt']
['Ranveer Singh' 'Alia Bhatt']
['Salman Khan' 'Alia Bhatt']
['Ajay Devgn' 'Alia Bhatt']
['Varun Dhawan' 'Alia Bhatt']
['Shraddha Kapoor' 'Alia Bhatt']
['Sunil Grover' 'Alia Bhatt']
['Hrithik Roshan' 'Alia Bhatt']
['Raj Arjun' 'Alia Bhatt']
['Aamir Khan' 'Alia Bhatt']
['Gurmeet Ram Rahim Singh' 'Alia Bhatt']
['Arsh Bajwa' 'Alia Bhatt']
['Rana Daggubati' 'Alia Bhatt']
['Naseeruddin Shah' 'Alia Bhatt']
['Kangana Ranaut' 'Alia Bhatt']
['Nana Patekar' 'Alia Bhatt']
['Arbaaz Khan' 'Alia Bhatt']
['Varun Dhawan' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Govinda' 'Alia Bhatt']
['Rajat Kapoor' 'Alia Bhatt']
['Anushka Sharma' 'Alia Bhatt']
['Kiara Advani' 'Alia Bhatt']
['Shaurya Singh' 'Alia Bhatt']
['Pankaj Tripathi' 'Alia Bhatt']
['Taapsee Pannu' 'Alia Bhatt']
['Adil Hussain' 'Alia Bhatt']
['Amitabh Bachchan' 'Alia Bhatt']
['Sunny Leone' 'Alia Bhatt']
['Hema Malini' 'Alia Bhatt']
['Raveena Tandon' 'Alia Bhatt']
['Amitabh Bachchan' 'Alia Bhatt']
['Amardeep Insan' 'Alia Bhatt']
['Shraddha Kapoor' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Sachin Tendulkar' 'Alia Bhatt']
['Irrfan Khan' 'Alia Bhatt']
['Himansh Kohli' 'Alia Bhatt']
['Adil Hussain' 'Alia Bhatt']
['Jayesh Raj' 'Alia Bhatt']
['Manisha Koirala' 'Alia Bhatt']
['Deepika Padukone' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Salman Khan' 'Alia Bhatt']
['Riteish Deshmukh' 'Alia Bhatt']
['Shiv Darshan' 'Alia Bhatt']
['Ranbir Kapoor' 'Alia Bhatt']
['Ashish Bisht' 'Alia Bhatt']
['Aahana Kumra' 'Alia Bhatt']
['Manoj Babani' 'Alia Bhatt']
['Rajveer Ankur Singh' 'Alia Bhatt']
['Kirti Kulhari' 'Alia Bhatt']
['Shah Rukh Khan' 'Alia Bhatt']
['Tiger Shroff' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Anil Kapoor' 'Alia Bhatt']
['Kartik Aaryan' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Prisha Aneja' 'Alia Bhatt']
['Aadar Jain' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Kunal Kapoor' 'Alia Bhatt']
['Arjun Rampal' 'Alia Bhatt']
['Kangana Ranaut' 'Alia Bhatt']
['Farhan Akhtar' 'Alia Bhatt']
['Sidharth Malhotra' 'Alia Bhatt']
['Hugh Bonneville' 'Alia Bhatt']
['Rishi Kapoor' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Kunaal Roy Kapur' 'Alia Bhatt']
['Sunny Leone' 'Alia Bhatt']
['Shraddha Kapoor' 'Alia Bhatt']
['Rina Charaniya' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Sunny Deol' 'Alia Bhatt']
['Sridevi' 'Alia Bhatt']
['Saif Ali Khan' 'Alia Bhatt']
['Soundarya Sharma' 'Alia Bhatt']
['Sudha Chandran' 'Alia Bhatt']
['Manoj Bajpayee' 'Alia Bhatt']
['Zaira Wasim' 'Alia Bhatt']
['Prakash Belawadi' 'Alia Bhatt']
['Kalki Koechlin' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Richa Chadha' 'Alia Bhatt']
['Irrfan Khan' 'Alia Bhatt']
['Zareen Khan' 'Alia Bhatt']
['Nayna Bandhopadhyay' 'Alia Bhatt']
['Vidya Balan' 'Alia Bhatt']
['Nishikant Kamat' 'Alia Bhatt']
['Sanjay Mishra' 'Alia Bhatt']
['Kapil Sharma' 'Alia Bhatt']
['Pulkit Samrat' 'Alia Bhatt']
['Vijay Varma' 'Alia Bhatt']
['Sushama Deshpande' 'Alia Bhatt']
['Richa Chadha' 'Alia Bhatt']
['Prince Shah' 'Alia Bhatt']
['Tanima Bhattacharya' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Zeenat Aman' 'Alia Bhatt']
['Madhavan' 'Alia Bhatt']
['Tusshar Kapoor' 'Alia Bhatt']
['Tusshar Kapoor' 'Alia Bhatt']
['Himansh Kohli' 'Alia Bhatt']
['Sadhana Singh' 'Alia Bhatt']
['Sunny Deol' 'Alia Bhatt']
['Aditya Roy Kapoor' 'Alia Bhatt']
['Rishi Kapoor' 'Alia Bhatt']
['Rajniesh Duggall' 'Alia Bhatt']
['Krishna Chaturvedi' 'Alia Bhatt']
['Girish Taurani' 'Alia Bhatt']
['Sonam Kapoor' 'Alia Bhatt']
['Sukhesh Arora' 'Alia Bhatt']
['Raima Sen' 'Alia Bhatt']
['Anuj Sachdeva' 'Alia Bhatt']
['Parthaa Akerkar' 'Alia Bhatt']
['Priyanka Chopra' 'Alia Bhatt']
['Sidharth Malhotra' 'Alia Bhatt']
['John Abraham' 'Alia Bhatt']
['Patralekhaa Paul' 'Alia Bhatt']
['Shah Rukh Khan' 'Alia Bhatt']
['Swara Bhaskar' 'Alia Bhatt']
['Randeep Hooda' 'Alia Bhatt']
['Shraddha Kapoor' 'Alia Bhatt']
['Pankaj Tripathi' 'Alia Bhatt']
['Jimmy Sheirgill' 'Alia Bhatt']
['Kartik Elangovan' 'Alia Bhatt']
['Boman Irani' 'Alia Bhatt']
['Manoj Bajpayee' 'Alia Bhatt']
['Sharman Joshi' 'Alia Bhatt']
['Emraan Hashmi' 'Alia Bhatt']
['Aanchal Dwivedi' 'Alia Bhatt']
['Sanjay Singh' 'Alia Bhatt']
['Arvind Swamy' 'Alia Bhatt']
['Radhika Apte' 'Alia Bhatt']
['Randeep Hooda' 'Alia Bhatt']
['Sachiin Joshi' 'Alia Bhatt']
['Kajal Aggarwal' 'Alia Bhatt']
['Amitabh Bachchan' 'Alia Bhatt']
['Shahid Kapoor' 'Alia Bhatt']
['Hazel Croney' 'Alia Bhatt']
['V. Ravichandran' 'Alia Bhatt']
['Vipin Sharma' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Pulkit Samrat' 'Alia Bhatt']
['Tannishtha Chatterjee' 'Alia Bhatt']
['Krrish Chhabria' 'Alia Bhatt']
['Avinash Dhyani' 'Alia Bhatt']
['Zeenat Aman' 'Alia Bhatt']
['Salman Khan' 'Alia Bhatt']
['Shashank Arora' 'Alia Bhatt']
['Urvashi Rautela' 'Alia Bhatt']
['Naseeruddin Shah' 'Alia Bhatt']
['Sara Loren' 'Alia Bhatt']
['Tom Alter' 'Alia Bhatt']
['Irrfan Khan' 'Alia Bhatt']
['John Abraham' 'Alia Bhatt']
['Rajeev Khandelwal' 'Alia Bhatt']
["Ileana D'Cruz" 'Alia Bhatt']
['Sahil Anand' 'Alia Bhatt']
['Hrithik Roshan' 'Alia Bhatt']
['Diana Penty' 'Alia Bhatt']
['Niharica Raizada' 'Alia Bhatt']
['Tiger Shroff' 'Alia Bhatt']
['Sidharth Malhotra' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Emraan Hashmi' 'Alia Bhatt']
['Taapsee Pannu' 'Alia Bhatt']
['Tannishtha Chatterjee' 'Alia Bhatt']
['Riteish Deshmukh' 'Alia Bhatt']
['Yash Soni' 'Alia Bhatt']
['Shreyas Talpade' 'Alia Bhatt']
['Vinay Pathak' 'Alia Bhatt']
['Jimmy Sharma' 'Alia Bhatt']
['Sushant Singh Rajput' 'Alia Bhatt']
['Ashok Insan' 'Alia Bhatt']
['RJ Balaji' 'Alia Bhatt']
['Saurav Chakraborty' 'Alia Bhatt']
['Shashank Udapurkar' 'Alia Bhatt']
['Shubham' 'Alia Bhatt']
['Manoj Bajpayee' 'Alia Bhatt']
['Sunny Leone' 'Alia Bhatt']
['Aashish Bhatt' 'Alia Bhatt']
['Ajay Devgn' 'Alia Bhatt']
['Ronit Roy' 'Alia Bhatt']
['Ranbir Kapoor' 'Alia Bhatt']
['Neha Sharma' 'Alia Bhatt']
['Farhan Akhtar' 'Alia Bhatt']
['John Abraham' 'Alia Bhatt']
['Alia Bhatt' 'Alia Bhatt']
['Vaani Kapoor' 'Alia Bhatt']
['Neha Dhupia' 'Alia Bhatt']
['Jimmy Sheirgill' 'Alia Bhatt']
['Sonarika Bhadoria' 'Alia Bhatt']
['Amitabh Bachchan' 'Alia Bhatt']
['Sharman Joshi' 'Alia Bhatt']
['Aamir Khan' 'Alia Bhatt']
['Harshvardhan Kapoor' 'Alia Bhatt']
['Salman Khan' 'Alia Bhatt']
['Kangana Ranaut' 'Alia Bhatt']
['Kangana Ranaut' 'Alia Bhatt']
['Soha Ali Khan' 'Alia Bhatt']
['Prabhu Deva' 'Alia Bhatt']
['Shah Rukh Khan' 'Alia Bhatt']
['Salman Khan' 'Alia Bhatt']
['Ranveer Singh' 'Alia Bhatt']
['Anil Kapoor' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Shakti Kapoor' 'Alia Bhatt']
['Bipasha Basu' 'Alia Bhatt']
['Arjun Kapoor' 'Alia Bhatt']
['Zayed Khan' 'Alia Bhatt']
['Malaika Arora' 'Alia Bhatt']
['Naman Jain' 'Alia Bhatt']
['Gurmeet Choudhary' 'Alia Bhatt']
['Kay Kay Menon' 'Alia Bhatt']
['Rati Agnihotri' 'Alia Bhatt']
['Amitabh Bachchan' 'Alia Bhatt']
['Arjun Rampal' 'Alia Bhatt']
['Varun Dhawan' 'Alia Bhatt']
['Swanand Kirkire' 'Alia Bhatt']
['Sulabha Arya' 'Alia Bhatt']
['Irrfan Khan' 'Alia Bhatt']
['Nana Patekar' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Anupam Kher' 'Alia Bhatt']
['Gurmeet Ram Rahim Singh' 'Alia Bhatt']
['Sidhant Gupta' 'Alia Bhatt']
['Arjun Mathur' 'Alia Bhatt']
['Ganesh Acharya' 'Alia Bhatt']
['Anushka Sharma' 'Alia Bhatt']
['Gulshan Devaiah' 'Alia Bhatt']
['Sushant Singh Rajput' 'Alia Bhatt']
['Adhyayan Suman' 'Alia Bhatt']
['Vira Sathidar' 'Alia Bhatt']
['Kalki Koechlin' 'Alia Bhatt']
['Sunny Leone' 'Alia Bhatt']
['Sara Loren' 'Alia Bhatt']
['Emraan Hashmi' 'Alia Bhatt']
['Auroshika Dey' 'Alia Bhatt']
['Ira Dubey' 'Alia Bhatt']
['Naseeruddin Shah' 'Alia Bhatt']
['Vinay Pathak' 'Alia Bhatt']
['Ram Kapoor' 'Alia Bhatt']
['Deepika Padukone' 'Alia Bhatt']
['Ranbir Kapoor' 'Alia Bhatt']
['Shakti Anand' 'Alia Bhatt']
['Anil Kapoor' 'Alia Bhatt']
['Arshad Warsi' 'Alia Bhatt']
['Meenakshi Dixit' 'Alia Bhatt']
['Yash Acharya' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Rahul Bagga' 'Alia Bhatt']
['Mohit Baghel' 'Alia Bhatt']
['Rishi Verma' 'Alia Bhatt']
['Mimoh Chakraborty' 'Alia Bhatt']
['Swara Bhaskar' 'Alia Bhatt']
['Richa Chadha' 'Alia Bhatt']
['Arshad Warsi' 'Alia Bhatt']
['Mugdha Godse' 'Alia Bhatt']
['Yashpal Sharma' 'Alia Bhatt']
['Dharmendra' 'Alia Bhatt']
['Sunny Deol' 'Alia Bhatt']
['Smitha Gondkar' 'Alia Bhatt']
['Kunal Kapoor' 'Alia Bhatt']
['Ajay Devgn' 'Alia Bhatt']
['Jacqueline Fernandez' 'Alia Bhatt']
['Rishi Kapoor' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Vinay Pathak' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Bhavita Anand' 'Alia Bhatt']
['Saif Ali Khan' 'Alia Bhatt']
['Suraj Pancholi' 'Alia Bhatt']
['Shamim Khan' 'Alia Bhatt']
['Irrfan Khan' 'Alia Bhatt']
['Suhaas Ahuja' 'Alia Bhatt']
['Jaideep Ahlawat' 'Alia Bhatt']
['Charanpreet Insan' 'Alia Bhatt']
['Akanksha Puri' 'Alia Bhatt']
['Kunal Khemu' 'Alia Bhatt']
['Aishwarya Rai Bachchan' 'Alia Bhatt']
['Seema Azmi' 'Alia Bhatt']
['Parveen Kaur' 'Alia Bhatt']
['Kapil Sharma' 'Alia Bhatt']
['Kartik Aaryan' 'Alia Bhatt']
['Diganth' 'Alia Bhatt']
['Shahid Kapoor' 'Alia Bhatt']
['Nawazuddin Siddiqui' 'Alia Bhatt']
['Kunal Khemu' 'Alia Bhatt']
['Mann Bagga' 'Alia Bhatt']
['Manish Paul' 'Alia Bhatt']
['Sanjeev Kumar' 'Alia Bhatt']
['Madhuri Dixit' 'Alia Bhatt']
['Shiv Darshan' 'Alia Bhatt']
['Gopi Desai' 'Alia Bhatt']
['Mohinder Gujral' 'Alia Bhatt']
['Zeenat Aman' 'Alia Bhatt']
['Ranveer Singh' 'Alia Bhatt']
['Salman Khan' 'Alia Bhatt']
['Sidharth Malhotra' 'Alia Bhatt']
['Adhyayan Suman' 'Alia Bhatt']
['Indrapal Ahuja' 'Alia Bhatt']
['Jimmy Sheirgill' 'Alia Bhatt']
['Abhay Deol' 'Alia Bhatt']
['Sahil Anand' 'Alia Bhatt']
['Alia Bhatt' 'Alia Bhatt']
['Sampat Pal Devi' 'Alia Bhatt']
['Farhan Akhtar' 'Alia Bhatt']
['Madhuri Dixit' 'Alia Bhatt']
['Kangana Ranaut' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Ali Zafar' 'Alia Bhatt']
['Mahek Chahal' 'Alia Bhatt']
['Monali Thakur' 'Alia Bhatt']
['Sunny Leone' 'Alia Bhatt']
['Harman Baweja' 'Alia Bhatt']
['Sanjay Mishra' 'Alia Bhatt']
['Sharman Joshi' 'Alia Bhatt']
['Sachin Khedekar' 'Alia Bhatt']
['Leeza Mangaldas' 'Alia Bhatt']
['Pulkit Samrat' 'Alia Bhatt']
['Zara Sheikh' 'Alia Bhatt']
['Arjun Kapoor' 'Alia Bhatt']
['Purab Kohli' 'Alia Bhatt']
['Amitabh Bachchan' 'Alia Bhatt']
['Varun Dhawan' 'Alia Bhatt']
['Arvinder Bhatti' 'Alia Bhatt']
['Kanika Batra' 'Alia Bhatt']
['Jackky Bhagnani' 'Alia Bhatt']
['Rajeev Khandelwal' 'Alia Bhatt']
['Tanuj Virwani' 'Alia Bhatt']
['Vijay Raaz' 'Alia Bhatt']
['Kannan Arunachalam' 'Alia Bhatt']
['Anjori Alagh' 'Alia Bhatt']
['Satish Kaushik' 'Alia Bhatt']
['Rahul Bagga' 'Alia Bhatt']
['Himesh Reshammiya' 'Alia Bhatt']
['Farooq Shaikh' 'Alia Bhatt']
['Makrand Deshpande' 'Alia Bhatt']
['Eesha Agarwal' 'Alia Bhatt']
['Siddharth Gupta' 'Alia Bhatt']
['Tiger Shroff' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Sharib Hashmi' 'Alia Bhatt']
['Kangana Ranaut' 'Alia Bhatt']
['Kartik Aaryan' 'Alia Bhatt']
['Swara Bhaskar' 'Alia Bhatt']
['Simer Motiani' 'Alia Bhatt']
['Anshuman Jha' 'Alia Bhatt']
['Sidharth Malhotra' 'Alia Bhatt']
['Vidya Balan' 'Alia Bhatt']
['Saif Ali Khan' 'Alia Bhatt']
['Varun Dhawan' 'Alia Bhatt']
['Jay Bhanushali' 'Alia Bhatt']
['Armaan Jain' 'Alia Bhatt']
['Rajesh Khanna' 'Alia Bhatt']
['Vir Das' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Jimmy Sheirgill' 'Alia Bhatt']
['Reshmi Ghosh' 'Alia Bhatt']
['Akshay Oberoi' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Anupam Kher' 'Alia Bhatt']
['Rani Mukerji' 'Alia Bhatt']
['Emraan Hashmi' 'Alia Bhatt']
['Priyanka Chopra' 'Alia Bhatt']
['Bipasha Basu' 'Alia Bhatt']
['Deepika Padukone' 'Alia Bhatt']
['Sonam Kapoor' 'Alia Bhatt']
['Salil Acharya' 'Alia Bhatt']
['Salman Khan' 'Alia Bhatt']
['Saahil Prem' 'Alia Bhatt']
['Alieesa P Badresia' 'Alia Bhatt']
['Manoj Amarnani' 'Alia Bhatt']
['Sasha Aagha' 'Alia Bhatt']
['Tabu' 'Alia Bhatt']
['Hrithik Roshan' 'Alia Bhatt']
['Rati Agnihotri' 'Alia Bhatt']
['Aditya Roy Kapoor' 'Alia Bhatt']
['Asrani' 'Alia Bhatt']
['Harshvardhan Deo' 'Alia Bhatt']
['Nikhil Dwivedi' 'Alia Bhatt']
['Karanvir Bohra' 'Alia Bhatt']
['Puru Chibber' 'Alia Bhatt']
['Soha Ali Khan' 'Alia Bhatt']
['Rhea Chakraborty' 'Alia Bhatt']
['Shah Rukh Khan' 'Alia Bhatt']
['Rekha' 'Alia Bhatt']
['Anupam Kher' 'Alia Bhatt']
['Randeep Hooda' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Aadil Chahal' 'Alia Bhatt']
['Shabana Azmi' 'Alia Bhatt']
['Dimple Kapadia' 'Alia Bhatt']
['Nishant Dahiya' 'Alia Bhatt']
['Ranveer Singh' 'Alia Bhatt']
['Emraan Hashmi' 'Alia Bhatt']
['Saif Ali Khan' 'Alia Bhatt']
['Vinod Acharya' 'Alia Bhatt']
['Mannara Chopra' 'Alia Bhatt']
['Prabhas' 'Alia Bhatt']
['Mischa Barton' 'Alia Bhatt']
['Shiv Panditt' 'Alia Bhatt']
['Annu Kapoor' 'Alia Bhatt']
['Barun Sobti' 'Alia Bhatt']
['Rahul Bhat' 'Alia Bhatt']
['Aamir Khan' 'Alia Bhatt']
['Adhyayan Suman' 'Alia Bhatt']
['Imran Khan' 'Alia Bhatt']
['Naveen Kasturia' 'Alia Bhatt']
['Arjun Rampal' 'Alia Bhatt']
['Sarita Joshi' 'Alia Bhatt']
['Kartik Aaryan' 'Alia Bhatt']
['Juhi Chawla' 'Alia Bhatt']
['Saif Ali Khan' 'Alia Bhatt']
['Manisha Kelkar' 'Alia Bhatt']
['Farooq Shaikh' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Randeep Hooda' 'Alia Bhatt']
['Vivek Oberoi' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Akash' 'Alia Bhatt']
['Vishwa Mohan Badola' 'Alia Bhatt']
['Neil Nitin Mukesh' 'Alia Bhatt']
['Saqib Saleem' 'Alia Bhatt']
['Arshad Warsi' 'Alia Bhatt']
['Jimmy Sheirgill' 'Alia Bhatt']
['Asha Bhosle' 'Alia Bhatt']
['Kamal Haasan' 'Alia Bhatt']
['Jackky Bhagnani' 'Alia Bhatt']
['Aditya Roy Kapoor' 'Alia Bhatt']
['Emraan Hashmi' 'Alia Bhatt']
['Ajay Devgn' 'Alia Bhatt']
['Ayushmann Khurrana' 'Alia Bhatt']
['Vivek Oberoi' 'Alia Bhatt']
['Vidyut Jammwal' 'Alia Bhatt']
['Rani Mukerji' 'Alia Bhatt']
['Saif Ali Khan' 'Alia Bhatt']
['Riya Vij' 'Alia Bhatt']
['Arjun Kapoor' 'Alia Bhatt']
['Preity Zinta' 'Alia Bhatt']
['Veena Malik' 'Alia Bhatt']
['Ranbir Kapoor' 'Alia Bhatt']
['Pulkit Samrat' 'Alia Bhatt']
['Rupa Bhimani' 'Alia Bhatt']
['Dhanush' 'Alia Bhatt']
['Kay Kay Menon' 'Alia Bhatt']
['Neil Nitin Mukesh' 'Alia Bhatt']
['Vidya Balan' 'Alia Bhatt']
['Anupam Kher' 'Alia Bhatt']
['Sanjay Dutt' 'Alia Bhatt']
['Farhan Akhtar' 'Alia Bhatt']
['Wamiqa Gabbi' 'Alia Bhatt']
['Shadab Kamal' 'Alia Bhatt']
['Sunil Shetty' 'Alia Bhatt']
['Prateik' 'Alia Bhatt']
['Tusshar Kapoor' 'Alia Bhatt']
['Tanuj Virwani' 'Alia Bhatt']
['Poonam Pandey' 'Alia Bhatt']
['Deepak Dobriyal' 'Alia Bhatt']
['Hemant Gopal' 'Alia Bhatt']
['Joy Mukherjee' 'Alia Bhatt']
['Rishi Kapoor' 'Alia Bhatt']
['Rajesh Tailang' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['John Abraham' 'Alia Bhatt']
['Amitabh Bachchan' 'Alia Bhatt']
['Sushant Singh Rajput' 'Alia Bhatt']
['Shruti Haasan' 'Alia Bhatt']
['Deepika Padukone' 'Alia Bhatt']
['Vivek Oberoi' 'Alia Bhatt']
['Naseeruddin Shah' 'Alia Bhatt']
['Karan Kundrra' 'Alia Bhatt']
['Shahid Kapoor' 'Alia Bhatt']
['Aida Elkashef' 'Alia Bhatt']
['Irrfan Khan' 'Alia Bhatt']
['Anisa Butt' 'Alia Bhatt']
['Akshay Kumar' 'Alia Bhatt']
['Rajkummar Rao' 'Alia Bhatt']
['Manish Paul' 'Alia Bhatt']

In [90]:
# arithematic operator (broadcasting)

print(100 - custom)

maths      33
science    31
english     1
french     90
sst         0
dtype: int64

In [92]:
# Relational operators
print(vk >=50 )

           runs
match_no
8         False
87        False
93        False
91        False
206       False
...         ...
164        True
120        True
123        True
126        True
128        True

[215 rows x 1 columns]